/**
 * Unique GitHub owner/repo pairs extracted from the team chat transcript (issue + repo links).
 * Used by POST /api/blacklistrepos to bulk blacklist whole repositories.
 */
export const CHAT_BLACKLIST_REPOS: readonly { owner: string; repo: string }[] = [
  { owner: 'alexgolec', repo: 'schwab-py' },
  { owner: 'andialbrecht', repo: 'sqlparse' },
  { owner: 'beeware', repo: 'toga' },
  { owner: 'cookiecutter', repo: 'cookiecutter' },
  { owner: 'databrickslabs', repo: 'dbx' },
  { owner: 'dosisod', repo: 'refurb' },
  { owner: 'eliben', repo: 'pyelftools' },
  { owner: 'erotemic', repo: 'ubelt' },
  { owner: 'gorakhargosh', repo: 'watchdog' },
  { owner: 'h2non', repo: 'pook' },
  { owner: 'ipython', repo: 'traitlets' },
  { owner: 'jborean93', repo: 'smbprotocol' },
  { owner: 'jd', repo: 'tenacity' },
  { owner: 'jazzband', repo: 'pip-tools' },
  { owner: 'joke2k', repo: 'faker' },
  { owner: 'jquast', repo: 'blessed' },
  { owner: 'mandiant', repo: 'capa' },
  { owner: 'mpmath', repo: 'mpmath' },
  { owner: 'pallets', repo: 'flask' },
  { owner: 'pymodbus-dev', repo: 'pymodbus' },
  { owner: 'pylint-dev', repo: 'pylint' },
  { owner: 'python-attrs', repo: 'attrs' },
  { owner: 'python-gitlab', repo: 'python-gitlab' },
  { owner: 'python-hyper', repo: 'wsproto' },
  { owner: 'python-pendulum', repo: 'pendulum' },
  { owner: 'python-rope', repo: 'rope' },
  { owner: 'python-trio', repo: 'trio' },
  { owner: 'python-validators', repo: 'validators' },
  { owner: 'tinche', repo: 'aiofiles' },
  { owner: 'tmbo', repo: 'questionary' },
  { owner: 'tox-dev', repo: 'tox' },
  { owner: 'tqdm', repo: 'tqdm' },
  { owner: 'wemake-services', repo: 'wemake-python-styleguide' },
].sort((a, b) => `${a.owner}/${a.repo}`.localeCompare(`${b.owner}/${b.repo}`));
